In [1]:
import sys,os
sys.path.append('..')
from ccat_holo.Pyccat_half import CCAT_holo_half
import time
import torch as T
import numpy as np
import h5py

c:\ProgramData\anaconda3\envs\ccatholo\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
dz_Rx=715
# 1. Model folder
Model_folder='../CCAT_model_Half'
# 2. Configuration of the Holography system
holo_setup={'Rx1':([0,0,dz_Rx],'../scan/501/on-axis.txt'), 
            'Rx2':([400,400,dz_Rx],'../scan/501/pos_pos_near.txt'),
            'Rx3':([400,-400,dz_Rx],'../scan/501/pos_neg_near.txt'),
            'Rx4':([-400,400,dz_Rx],'../scan/501/neg_pos_near.txt'),
            'Rx5':([-400,-400,dz_Rx],'../scan/501/neg_neg_near.txt')
            }
# Define 5 receiver positions in the 'Coord_Rx' system, e.g [+/-400,+/-400,600]
# and their field points that are stored in file 'scan/400_400_600.txt'. The field
# points of the measured beam maps are from the read out of the telescope coders.
#####################
# 3. Output_folder is the folder used to store the intermediate data of the first
#    beam calculation and the analysing results.
Output_folder='test_tensor'

# 4. Create the FYST holography Model and check the telescope model and 
# holographic setup in the 3D view.
Model=CCAT_holo_half(Model_folder,Output_folder,holo_conf=holo_setup)

FYST telescope model has been created!!


In [3]:
Model.view() # Show 3D FYST model and its receivers.
Model.CF_view()
Model.view_Rx(Rx=['Rx1']) # This method can highlight the chosen reciever horns.


[-1.2490457723982542, 0, 0] [0, -4799.999999999999, 0]


Widget(value='<iframe src="http://localhost:63808/index.html?ui=P_0x2354867af10_0&reconnect=auto" class="pyvis…

[-3198.5  -350.   -350.  -3198.5] [-5827.74023955 -5827.74023955 -3772.25976045 -3772.25976045] [ 3083.22071866  3083.22071866 -3083.22071866 -3083.22071866]
[-2998.5  -335.   -335.  -2998.5] [-2985.15074996 -2985.15074996  2985.15074996  2985.15074996] [5092.57537498 5092.57537498 2107.42462502 2107.42462502]


In [4]:
N_m2=1
faces2=np.ones(N_m2).astype(int)*4
factor=np.linspace(0,4*N_m2-1,4*N_m2).astype(int).reshape(-1,4)
#faces2=np.c_[faces2,factor].ravel()

In [5]:
faces2

array([4])

In [6]:
np.c_[faces2,factor]

array([[4, 0, 1, 2, 3]])